GET  http://localhost:8000/profesion
###

POST http://localhost:8000/profesion
Content-Type: application/json

{
  "nombre_profesion": "Ciencias"
}
###
PUT http://localhost:8000/profesion
Content-Type: application/json

{
  "id_profesion": "1",
  "nombre_profesion": "Nadaaaaa"
}
###
DELETE http://localhost:8000/profesion/1