GET  http://localhost:8000/instructor
###

POST http://localhost:8000/instructor
Content-Type: application/json

{
  "nombre": "Osman",
  "apellido": "Aranguren",
  "email": "osman123@gmail.com",
  "telefono": "3123423232"
}
###
PUT http://localhost:8000/instructor
Content-Type: application/json

{
  "id_instructor": "2",
  "nombre": "Osman",
  "apellido": "Escobar",
  "email": "osman123@gmail.com",
  "telefono": "3123423232"
}
###
DELETE http://localhost:8000/instructor/3