GET  http://localhost:8000/ficha
###

POST http://localhost:8000/ficha
Content-Type: application/json

{
  
    "codigo": "29132122",
    "fecha_inicio_lectiva": "2023-01-01" ,
    "fecha_fin_lectiva": "2023-12-31" ,
    "fecha_fin_practica": "2024-05-31" ,
    "id_programa": 1

}
###


PUT http://localhost:8000/ficha
Content-Type: application/json

{
    "id_ficha": 1,
    "codigo": "0000",
    "fecha_inicio_lectiva": "2023-01-01" ,
    "fecha_fin_lectiva": "2023-12-31" ,
    "fecha_fin_practica": "2024-05-31",
    "id_programa": "1"


}
###

DELETE http://localhost:8000/ficha/1

