GET  http://localhost:8000/instructor
###

POST http://localhost:8000/instructor
Content-Type: application/json

{
  "name": "John Doe",
  "email": ""
}
###
PUT http://localhost:8000/instructor
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": ""
}
###
DELETE http://localhost:8000/instructor/1