GET http://localhost:8000/programa
###

POST http://localhost:8000/programa
Content-Type: application/json

{
"programa": "Electricidad Industrial"
}
###

PUT http://localhost:8000/programa
Content-Type: application/json

{
"id": "3",
"programa": "Electricidad Industrial Sena"
}